# Generated by Django 4.2.30 on 2026-04-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('dosha_suitability', models.CharField(help_text='e.g., Vata, Pitta, Kapha, Tridoshic', max_length=200)),
                ('contraindications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
