# Generated by Django 4.2.30 on 2026-04-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Fulfillment'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20),
        ),
    ]
